### PR TITLE
Add external Id as optional arg for sts:assumeRole

### PR DESCRIPTION
**Pull request by aperov9**
Hi,

I added the option to provide an external ID when assuming the role in each target account. The external ID is an optional argument that can be passed when calling sts:assumeRole.

Main use case is when you are using a custom AWS Role for getting access to each target account. This custom role has in its Trust Policy a conditional statement that only allows assuming the role by passing a specific external ID.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::<ACCOUNT_ID>:root"
            },
            "Action": "sts:AssumeRole",
            "Condition": {
                "StringEquals": {
                    "sts:ExternalId": "<SOME_STRING>"
                }
            }
        }
    ]
}
```

For more information check out the official AWS docs: 
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html

### CODE REVIEW

**Comment by iainelder** [comment]
Thanks for this @aperov9 . I will try it when I have a moment.

**Comment by iainelder** [comment]
It looks good to me.

**Review by connelldave — APPROVED** [review]
lgtm!

**Comment by connelldave** [comment]
Can you add a line to the readme and a 1.6.4 changelog note and we can cut a release :)

**Comment by aperov9** [comment]
Changelog and Readme have been adjusted

**Comment by connelldave** [comment]
Released as 1.6.4 - thanks! :)

**Pull request merged**
