### PR TITLE
Botocove leaks memory when main session has no region set

### PR DESCRIPTION
**Pull request by iainelder**
See the [missing_region_memory_leak_demo/README.md](missing_region_memory_leak_demo/README.md) for the details.

This is what was tripping me up in #39.

Do you understand why this happens? I can't make sense of it. But I do see that the size of the leak depends on the client. EC2 is a more complex service than say the IAM service, so its client needs more memory.

And do you know how it might be avoided? It's an edge case, but I'd like the memory use not risk destabilizing my computer because of a careless mistake with an environment variable.

(One workaround may be to develop with raise_exceptions=True until confident that everything is set up correctly.)

Is a draft PR the right way to share this kind of finding? My intention isn't to merge this, although there are some ideas here that could be reusable. Mainly I wanted to share my branch with you in a way that is clear via the Github interface.

### CODE REVIEW

**Comment by connelldave** [comment]
So this PR was cut on the day of my wedding :D I didn't mean to ignore it.. however - I can't repro either! I don't get a memory leak either way. Perhaps an OSX vs *nix issue?

**Comment by connelldave** [comment]
A quick and dirty dockerfile (with some copy paste magic to work on an M1 mac) also works - perhaps a bug fixed between our deps somewhere?
```
FROM python:3.8-slim-buster
RUN apt-get update -q \
    && apt-get install --no-install-recommends -qy python3-dev g++ gcc inetutils-ping
RUN pip install poetry
COPY ./ .
RUN poetry install
```
(built and run a bash entrypoint then run as described)

**Comment by iainelder** [comment]
I've not tried to reproduce it since I published this. I'll try again when I get a chance. If even I can't reproduce it with the latest versions, then we can just close it.

It's my own wedding day tomorrow so I will not be able to look at this again until next week at the earliest. 😀

**Comment by connelldave** [comment]
Congratulations to you and your partner! :) Have a great day!

**Comment by connelldave** [comment]
Closing as unreproducible - still worth referencing for adding a test harness for memory leak behaviour being introduced one day though!

**Pull request closed without merging**
